version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: ./
    ports:
      - 8001:8001
    volumes:
     - .:/var/www/html
     - vendor-store:/var/www/html/vendor
    working_dir: /var/www/html
    command : php artisan serve --host 0.0.0.0 --port 8001
    depends_on:
      - db

volumes:
  vendor-store: # add
  mysql-data:
